# mybatis
mybatis:
  mapper-locations: classpath*:mappings/**/*.xml
spring:
  datasource:
    url: jdbc:mysql://${your_key_db.host}:${your_key_db.port}/yourDbName?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&connectTimeout=1000&socketTimeout=60000&rewriteBatchedStatements=true
    username: ${your_key_db.user}
    password: ${your_key_db.password}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 5000
      validation-timeout: 3000
